# Generated by Django 5.2.5 on 2025-09-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrack', '0005_alter_product_currency_alter_product_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='affiliate_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='PriceAlert',
        ),
    ]
