# Generated by Django 5.2.5 on 2025-09-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrack', '0006_trackedproduct_threshold_alter_product_affiliate_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedproduct',
            name='threshold',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
