# Generated by Django 5.2.5 on 2025-09-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrack', '0007_alter_trackedproduct_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trackedproduct',
            name='threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
