# Generated by Django 5.2.5 on 2025-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrack', '0008_trackedproduct_active_alter_trackedproduct_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='repeat_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
