# Generated by Django 5.2.5 on 2025-09-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrack', '0009_trackedproduct_repeat_alerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, max_length=1024, null=True, unique=True),
        ),
    ]
