# Generated by Django 5.2.5 on 2025-09-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrack', '0010_remove_product_url_alter_product_product_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-date']},
        ),
    ]
