# Generated by Django 5.2.5 on 2025-09-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrack', '0011_alter_pricehistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedproduct',
            name='alert_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
