# Generated by Django 5.2.5 on 2025-10-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceTrack', '0012_trackedproduct_alert_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedproduct',
            name='alert_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
